### ISSUE TITLE
Read below

### ISSUE THREAD

**Issue by Codepulze** [TheCuteOwl/py_hmtai#1]
Add better readme!!!!!!!!!!!!! 😠

**Comment by TheCuteOwl** [comment]
Sorry i was bored, i will update the thing + the readme today or tomorrow ^^ it was just make for fun so well.. xD

**Comment by Codepulze** [comment]
I HOPE SO 😠 💢 😡

**Comment by TheCuteOwl** [comment]
xD

**Comment by TheCuteOwl** [comment]
I'm working on the readme, but btw, how did you found this repo?

**Comment by TheCuteOwl** [comment]
Readme updated.

**Comment by Codepulze** [comment]
idk i was just scrolling you might check mine :))

**Comment by Codepulze** [comment]
ok readme is good

**Comment by TheCuteOwl** [comment]
Well, as i can see, you saw me not from hm directly but more from another repository ig

**Comment by Codepulze** [comment]
yreah

**Comment by TheCuteOwl** [comment]
Trap stealer?

**Comment by Codepulze** [comment]
igg
